export const WEATHER_DATA = [
  { code: 200, main: "천둥번개", description: "뇌우와 약한 비" },
  { code: 201, main: "천둥번개", description: "뇌우와 비" },
  { code: 202, main: "천둥번개", description: "뇌우와 폭우" },
  { code: 210, main: "천둥번개", description: "약한 뇌우" },
  { code: 211, main: "천둥번개", description: "뇌우" },
  { code: 212, main: "천둥번개", description: "강한 뇌우" },
  { code: 221, main: "천둥번개", description: "불규칙한 뇌우" },
  { code: 230, main: "천둥번개", description: "뇌우와 약한 이슬비" },
  { code: 231, main: "천둥번개", description: "뇌우와 이슬비" },
  { code: 232, main: "천둥번개", description: "뇌우와 강한 이슬비" },
  { code: 300, main: "이슬비", description: "약한 이슬비" },
  { code: 301, main: "이슬비", description: "이슬비" },
  { code: 302, main: "이슬비", description: "강한 이슬비" },
  { code: 310, main: "이슬비", description: "약한 이슬비와 비" },
  { code: 311, main: "이슬비", description: "이슬비와 비" },
  { code: 312, main: "이슬비", description: "강한 이슬비와 비" },
  { code: 313, main: "이슬비", description: "소나기와 이슬비" },
  { code: 314, main: "이슬비", description: "강한 소나기와 이슬비" },
  { code: 321, main: "이슬비", description: "소나기 이슬비" },
  { code: 500, main: "비", description: "약한 비" },
  { code: 501, main: "비", description: "보통 비" },
  { code: 502, main: "비", description: "강한 비" },
  { code: 503, main: "비", description: "매우 강한 비" },
  { code: 504, main: "비", description: "극심한 비" },
  { code: 511, main: "비", description: "얼음 비" },
  { code: 520, main: "비", description: "약한 소나기" },
  { code: 521, main: "비", description: "소나기" },
  { code: 522, main: "비", description: "강한 소나기" },
  { code: 531, main: "비", description: "불규칙한 소나기" },
  { code: 600, main: "눈", description: "약한 눈" },
  { code: 601, main: "눈", description: "눈" },
  { code: 602, main: "눈", description: "강한 눈" },
  { code: 611, main: "눈", description: "슬렛" },
  { code: 612, main: "눈", description: "약한 소나기 눈" },
  { code: 613, main: "눈", description: "소나기 눈" },
  { code: 615, main: "눈", description: "약한 비와 눈" },
  { code: 616, main: "눈", description: "비와 눈" },
  { code: 620, main: "눈", description: "약한 소나기 눈" },
  { code: 621, main: "눈", description: "소나기 눈" },
  { code: 622, main: "눈", description: "강한 소나기 눈" },
  { code: 701, main: "안개", description: "안개" },
  { code: 711, main: "연기", description: "연기" },
  { code: 721, main: "안개 낀", description: "안개 낀" },
  { code: 731, main: "먼지 소용돌이", description: "모래/먼지 소용돌이" },
  { code: 741, main: "안개", description: "안개" },
  { code: 751, main: "모래", description: "모래" },
  { code: 761, main: "먼지", description: "먼지" },
  { code: 762, main: "화산재", description: "화산재" },
  { code: 771, main: "돌풍", description: "돌풍" },
  { code: 781, main: "토네이도", description: "토네이도" },
  { code: 800, main: "맑음", description: "맑음" },
  { code: 801, main: "약간 흐림", description: "약간 흐림: 11-25%" },
  { code: 802, main: "흩어진 구름", description: "흩어진 구름: 25-50%" },
  { code: 803, main: "흐림", description: "흐림: 51-84%" },
  { code: 804, main: "매우 흐림", description: "흐림: 85-100%" },
];

export const WEATHER_MEDIA_TEXT = {
  weather: ["현재 날씨는", "입니다"],
  temperature: ["현재 기온은", "입니다"],
  belongings: ["외출 시", "을 챙기세요"],
  outfit: ["오늘은", "를 추천해요"],
};
